version: "3"
services:

  build_env:
    build:
      context: .
      dockerfile: Dockerfile
      target: riscv_gnu_toolchain_dev_env 
      args:
        DOCKER_USER_UID: 1000
    image: five_embeddev/riscv_gnu_toolchain_dev_env
    command: ["riscv32-unknown-elf-gcc", "--version"]

  shell:
    image: five_embeddev/riscv_gnu_toolchain_dev_env
    volumes:
    - ./work:/work
    stdin_open: true # docker run -i
    tty: true        # docker run -t
    command: ["bash"]
 
