include ../common.mak

SPIKE_IMAGE_NAME=forked_riscv_spike_dev_env
IMAGE_NAME=forked_riscv_spike_debug_gdb
RELEASE_TAG:=${RELEASE_TAG}_spike_${SPIKE_TAG}

DOCKER_BUILD_ARGS += \
	SPIKE_IMAGE_NAME=${SPIKE_IMAGE_NAME}

all : docker-build-${IMAGE_NAME}

.PHONY: docker-build-${IMAGE_NAME}
docker-build-${IMAGE_NAME} : \
	riscv_spike.cfg \
	sim_helpers.sh \
	riscv-spike-vcd \
	riscv-openocd \
	riscv-xpack-gcc 

include ../targets.mak


