services:
  riscv_openocd:
    build:
      context : .
      target: riscv_openocd_base
    image: five_embeddev/riscv_openocd
    ports:
      - "9824:9824"
      - "4000:4000"
      - "6000:6000"
      - "3000:3000"
    command: ["openocd", "--version"]
      
  riscv_openocd_shell:
    image: five_embeddev/riscv_openocd
    command: bash
    tty: true
    stdin_open: true
