version: "3"
services:

  build_test_code: 
    build:
      context: .
      dockerfile: Dockerfile
      target: build_env
    volumes:
        - .:/project
    
  sim_test_code: 
    build:
      context: .
      dockerfile: Dockerfile
      target: sim_env
    volumes:
        - .:/project
