FROM five_embeddev/riscv_xpack_gcc_dev_env:latest AS build_env

WORKDIR /project/
RUN mkdir /project/build

# TODO - add something

# ------------------------------------------------------------------------
FROM five_embeddev/riscv_spike_dev_env:latest AS sim_env

WORKDIR /project/

# TODO - add something.

