version: "3"
services:

  build_env:
    build:
      context: .
      dockerfile: Dockerfile
      target: riscv_tools_build_env
      args:
        DOCKER_USER_UID: 1000
    image: five_embeddev/build_env
    command: ["gcc", "--version"]

  shell:
    depends_on:
    - build_env
    image: five_embeddev/build_env
    stdin_open: true # docker run -i
    tty: true        # docker run -t
    command: ["bash"]
 
